// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation.proto

package com.milind.grpc;

public interface ValidationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.milind.grpc.ValidationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string accountName = 1;</code>
   */
  java.lang.String getAccountName();
  /**
   * <code>optional string accountName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountNameBytes();

  /**
   * <code>optional string accountNumber = 2;</code>
   */
  java.lang.String getAccountNumber();
  /**
   * <code>optional string accountNumber = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccountNumberBytes();

  /**
   * <code>optional string routingNumber = 3;</code>
   */
  java.lang.String getRoutingNumber();
  /**
   * <code>optional string routingNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getRoutingNumberBytes();
}
