// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation.proto

package com.milind.grpc;

/**
 * Protobuf type {@code com.milind.grpc.ValidationResponse}
 */
public  final class ValidationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.milind.grpc.ValidationResponse)
    ValidationResponseOrBuilder {
  // Use ValidationResponse.newBuilder() to construct.
  private ValidationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidationResponse() {
    accountNameError_ = "";
    accountNumberError_ = "";
    routingNumberError_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ValidationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accountNameError_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            accountNumberError_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            routingNumberError_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.milind.grpc.Validation.internal_static_com_milind_grpc_ValidationResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.milind.grpc.Validation.internal_static_com_milind_grpc_ValidationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.milind.grpc.ValidationResponse.class, com.milind.grpc.ValidationResponse.Builder.class);
  }

  public static final int ACCOUNTNAMEERROR_FIELD_NUMBER = 1;
  private volatile java.lang.Object accountNameError_;
  /**
   * <code>optional string accountNameError = 1;</code>
   */
  public java.lang.String getAccountNameError() {
    java.lang.Object ref = accountNameError_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountNameError_ = s;
      return s;
    }
  }
  /**
   * <code>optional string accountNameError = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccountNameErrorBytes() {
    java.lang.Object ref = accountNameError_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountNameError_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTNUMBERERROR_FIELD_NUMBER = 2;
  private volatile java.lang.Object accountNumberError_;
  /**
   * <code>optional string accountNumberError = 2;</code>
   */
  public java.lang.String getAccountNumberError() {
    java.lang.Object ref = accountNumberError_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountNumberError_ = s;
      return s;
    }
  }
  /**
   * <code>optional string accountNumberError = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAccountNumberErrorBytes() {
    java.lang.Object ref = accountNumberError_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountNumberError_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUTINGNUMBERERROR_FIELD_NUMBER = 3;
  private volatile java.lang.Object routingNumberError_;
  /**
   * <code>optional string routingNumberError = 3;</code>
   */
  public java.lang.String getRoutingNumberError() {
    java.lang.Object ref = routingNumberError_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      routingNumberError_ = s;
      return s;
    }
  }
  /**
   * <code>optional string routingNumberError = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRoutingNumberErrorBytes() {
    java.lang.Object ref = routingNumberError_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      routingNumberError_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccountNameErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountNameError_);
    }
    if (!getAccountNumberErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountNumberError_);
    }
    if (!getRoutingNumberErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, routingNumberError_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccountNameErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountNameError_);
    }
    if (!getAccountNumberErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountNumberError_);
    }
    if (!getRoutingNumberErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, routingNumberError_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.milind.grpc.ValidationResponse)) {
      return super.equals(obj);
    }
    com.milind.grpc.ValidationResponse other = (com.milind.grpc.ValidationResponse) obj;

    boolean result = true;
    result = result && getAccountNameError()
        .equals(other.getAccountNameError());
    result = result && getAccountNumberError()
        .equals(other.getAccountNumberError());
    result = result && getRoutingNumberError()
        .equals(other.getRoutingNumberError());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ACCOUNTNAMEERROR_FIELD_NUMBER;
    hash = (53 * hash) + getAccountNameError().hashCode();
    hash = (37 * hash) + ACCOUNTNUMBERERROR_FIELD_NUMBER;
    hash = (53 * hash) + getAccountNumberError().hashCode();
    hash = (37 * hash) + ROUTINGNUMBERERROR_FIELD_NUMBER;
    hash = (53 * hash) + getRoutingNumberError().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.milind.grpc.ValidationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.milind.grpc.ValidationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.milind.grpc.ValidationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.milind.grpc.ValidationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.milind.grpc.ValidationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.milind.grpc.ValidationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.milind.grpc.ValidationResponse)
      com.milind.grpc.ValidationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.milind.grpc.Validation.internal_static_com_milind_grpc_ValidationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.milind.grpc.Validation.internal_static_com_milind_grpc_ValidationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.milind.grpc.ValidationResponse.class, com.milind.grpc.ValidationResponse.Builder.class);
    }

    // Construct using com.milind.grpc.ValidationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      accountNameError_ = "";

      accountNumberError_ = "";

      routingNumberError_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.milind.grpc.Validation.internal_static_com_milind_grpc_ValidationResponse_descriptor;
    }

    public com.milind.grpc.ValidationResponse getDefaultInstanceForType() {
      return com.milind.grpc.ValidationResponse.getDefaultInstance();
    }

    public com.milind.grpc.ValidationResponse build() {
      com.milind.grpc.ValidationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.milind.grpc.ValidationResponse buildPartial() {
      com.milind.grpc.ValidationResponse result = new com.milind.grpc.ValidationResponse(this);
      result.accountNameError_ = accountNameError_;
      result.accountNumberError_ = accountNumberError_;
      result.routingNumberError_ = routingNumberError_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.milind.grpc.ValidationResponse) {
        return mergeFrom((com.milind.grpc.ValidationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.milind.grpc.ValidationResponse other) {
      if (other == com.milind.grpc.ValidationResponse.getDefaultInstance()) return this;
      if (!other.getAccountNameError().isEmpty()) {
        accountNameError_ = other.accountNameError_;
        onChanged();
      }
      if (!other.getAccountNumberError().isEmpty()) {
        accountNumberError_ = other.accountNumberError_;
        onChanged();
      }
      if (!other.getRoutingNumberError().isEmpty()) {
        routingNumberError_ = other.routingNumberError_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.milind.grpc.ValidationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.milind.grpc.ValidationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accountNameError_ = "";
    /**
     * <code>optional string accountNameError = 1;</code>
     */
    public java.lang.String getAccountNameError() {
      java.lang.Object ref = accountNameError_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNameError_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string accountNameError = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameErrorBytes() {
      java.lang.Object ref = accountNameError_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNameError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string accountNameError = 1;</code>
     */
    public Builder setAccountNameError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountNameError_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string accountNameError = 1;</code>
     */
    public Builder clearAccountNameError() {
      
      accountNameError_ = getDefaultInstance().getAccountNameError();
      onChanged();
      return this;
    }
    /**
     * <code>optional string accountNameError = 1;</code>
     */
    public Builder setAccountNameErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountNameError_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accountNumberError_ = "";
    /**
     * <code>optional string accountNumberError = 2;</code>
     */
    public java.lang.String getAccountNumberError() {
      java.lang.Object ref = accountNumberError_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNumberError_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string accountNumberError = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNumberErrorBytes() {
      java.lang.Object ref = accountNumberError_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNumberError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string accountNumberError = 2;</code>
     */
    public Builder setAccountNumberError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountNumberError_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string accountNumberError = 2;</code>
     */
    public Builder clearAccountNumberError() {
      
      accountNumberError_ = getDefaultInstance().getAccountNumberError();
      onChanged();
      return this;
    }
    /**
     * <code>optional string accountNumberError = 2;</code>
     */
    public Builder setAccountNumberErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountNumberError_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object routingNumberError_ = "";
    /**
     * <code>optional string routingNumberError = 3;</code>
     */
    public java.lang.String getRoutingNumberError() {
      java.lang.Object ref = routingNumberError_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routingNumberError_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string routingNumberError = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRoutingNumberErrorBytes() {
      java.lang.Object ref = routingNumberError_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routingNumberError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string routingNumberError = 3;</code>
     */
    public Builder setRoutingNumberError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      routingNumberError_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string routingNumberError = 3;</code>
     */
    public Builder clearRoutingNumberError() {
      
      routingNumberError_ = getDefaultInstance().getRoutingNumberError();
      onChanged();
      return this;
    }
    /**
     * <code>optional string routingNumberError = 3;</code>
     */
    public Builder setRoutingNumberErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      routingNumberError_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.milind.grpc.ValidationResponse)
  }

  // @@protoc_insertion_point(class_scope:com.milind.grpc.ValidationResponse)
  private static final com.milind.grpc.ValidationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.milind.grpc.ValidationResponse();
  }

  public static com.milind.grpc.ValidationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidationResponse>
      PARSER = new com.google.protobuf.AbstractParser<ValidationResponse>() {
    public ValidationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValidationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidationResponse> getParserForType() {
    return PARSER;
  }

  public com.milind.grpc.ValidationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

