// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation.proto

package com.milind.grpc;

public interface ValidationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.milind.grpc.ValidationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string accountNameError = 1;</code>
   */
  java.lang.String getAccountNameError();
  /**
   * <code>optional string accountNameError = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountNameErrorBytes();

  /**
   * <code>optional string accountNumberError = 2;</code>
   */
  java.lang.String getAccountNumberError();
  /**
   * <code>optional string accountNumberError = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccountNumberErrorBytes();

  /**
   * <code>optional string routingNumberError = 3;</code>
   */
  java.lang.String getRoutingNumberError();
  /**
   * <code>optional string routingNumberError = 3;</code>
   */
  com.google.protobuf.ByteString
      getRoutingNumberErrorBytes();
}
