// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.milind.grpc;

public interface FileDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.milind.grpc.FileData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes content = 1;</code>
   */
  com.google.protobuf.ByteString getContent();
}
