// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.milind.grpc;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.milind.grpc.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string empList = 1;</code>
   */
  java.lang.String getEmpList();
  /**
   * <code>optional string empList = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmpListBytes();

  /**
   * <code>optional int64 totalEmp = 2;</code>
   */
  long getTotalEmp();

  /**
   * <code>optional int64 averageMarks = 3;</code>
   */
  long getAverageMarks();
}
