// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.milind.grpc;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.milind.grpc.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string empName = 1;</code>
   */
  java.lang.String getEmpName();
  /**
   * <code>optional string empName = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmpNameBytes();

  /**
   * <code>optional int64 marks = 2;</code>
   */
  long getMarks();
}
