// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.milind.grpc;

public interface UploadStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.milind.grpc.UploadStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string Message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string Message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional .com.milind.grpc.UploadStatusCode Code = 2;</code>
   */
  int getCodeValue();
  /**
   * <code>optional .com.milind.grpc.UploadStatusCode Code = 2;</code>
   */
  com.milind.grpc.UploadStatusCode getCode();
}
